-   id: pip-comile-lock
    name: check for added large files
    description: Compile requirements.[in|txt] into a locked dependency tree requirements file.
    entry: pip-comile-lock
    language: python
    stages: [commit, push, manual]