-   id: pip-comile-lock
    name: Compiling pip dependency graph
    description: Compile requirements.[in|txt] into a locked dependency tree requirements file.
    entry: pip-comile-lock
    language: python
    stages: [commit, push, manual]
-   id: run-pytest-cov
    name: Pytest & Coverage
    description: Run tests and coverage report
    entry: run-pytest-cov
    language: python
    stages: [commit, push, manual]