repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer


  # ###########################################################################################
  # [FORMAT]
  # Apply auto-formatting
  # ###########################################################################################
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: "Python | Sort Imports"
        args:
          - --color
        additional_dependencies:
          - colorama==0.4.5

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: "Python | Format"
        args:
          - --color
        language_version: python3.8.5

  # ###########################################################################################
  # [LINTING]
  # Apply auto-formatting (upgrade syntax for newer versions)
  # ###########################################################################################
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        name: "Python | Upgrade Syntax"
        args:
          - --py38-plus

  # ###########################################################################################
  # [LINTING]
  # ###########################################################################################
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: "Python | Linter (flake8)"
        additional_dependencies:
          - flake8-bugbear==22.4.25
          - flake8-comprehensions==3.10.0
          - flake8-simplify==0.19.3
          - flake8-colors==0.1.9
          - flake8-cognitive-complexity==0.1.0
          - flake8-functions==0.0.7
          - flake8-pytest-style==1.6.0
          - flake8-annotations==2.9.0
          - flake8-variables-names==0.0.5
          - flake8-builtins==1.5.3
          - pep8-naming==0.13.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        name: "Python | Linter (mypy)"

  # ###########################################################################################
  # [SECURITY]
  # Scan for common security issues
  # ###########################################################################################
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: "Python | Security Scan (bandit)"
        args: ["-c", "pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
